@echo off
echo GAM update user 18791@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 18675@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 18587@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 18549@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 18714@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19163@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19112@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19161@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19062@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 18981@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 18934@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19257@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19134@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19160@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19008@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 18916@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19188@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19000@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19143@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19157@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19021@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 18904@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19247@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 18957@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19063@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 18944@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19243@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19189@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19138@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 18995@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19141@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19185@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 18991@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 18986@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 18912@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19121@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19145@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 18973@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 18955@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 18913@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19106@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19223@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19262@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19270@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19613@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19500@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19425@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19509@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19435@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19368@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19623@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19342@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19511@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19629@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19508@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19580@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19558@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19631@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19553@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19356@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19323@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19499@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19627@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19634@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19407@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19532@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19614@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19585@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19354@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19445@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19295@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19426@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19398@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19523@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19491@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19285@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19271@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19636@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19608@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19334@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19624@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19531@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19486@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19297@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19526@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19444@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19286@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19470@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19403@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19458@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19337@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19490@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19514@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19605@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19517@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19467@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19461@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19616@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19331@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19462@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19535@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19633@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19394@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19301@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19515@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19481@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19413@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19512@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19319@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19598@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19276@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19312@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19298@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19564@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19316@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19510@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19632@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19599@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19498@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19418@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19637@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19547@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19404@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19305@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19582@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19373@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19576@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19586@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19409@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19571@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19380@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19411@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19365@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19446@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19453@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19433@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19533@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19397@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19341@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19549@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19618@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19478@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19288@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19505@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19313@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19364@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19399@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19641@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19450@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19604@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19454@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19595@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19640@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19401@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19329@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19357@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19463@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19477@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19437@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19362@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19516@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19560@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19292@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19464@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19530@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19626@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19447@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19309@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19423@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19474@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19335@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19392@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19369@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19518@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19371@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19537@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19443@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19559@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19485@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19455@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19420@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19317@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19374@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19325@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19451@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19587@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19333@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19296@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19351@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19405@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19349@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19476@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19520@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19304@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19306@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19294@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19358@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19417@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19471@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19355@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19363@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19421@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19322@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19449@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19282@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19592@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19277@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19283@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19492@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19424@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19279@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19619@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19289@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19367@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19361@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19473@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19546@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19561@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19607@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19480@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19293@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19284@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19542@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19456@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19617@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19457@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19375@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19274@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19570@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19479@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19575@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19275@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19422@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19345@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19406@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19428@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19300@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19287@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19525@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19502@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19524@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19548@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19482@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19568@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19565@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19642@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19649@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19650@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19653@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19652@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19655@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19661@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19684@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19680@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19691@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19692@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19693@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19696@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 19700@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 20070@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 20072@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 20073@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 20074@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 20075@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 20077@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 20544@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 20550@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 20551@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 20553@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 20557@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 21029@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 21027@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 21020@marconiverona.edu.it org /studenti.diplomati
echo GAM update user 21045@marconiverona.edu.it org /studenti.diplomati
