# Generated by Django 5.0.7 on 2025-11-02 14:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piva', models.CharField(max_length=16)),
                ('nome', models.CharField(max_length=64)),
                ('descrizione', models.TextField()),
            ],
            options={
                'verbose_name': 'Azienda',
                'verbose_name_plural': 'Aziende',
            },
        ),
        migrations.CreateModel(
            name='Progetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField()),
                ('requisiti', models.TextField(blank=True, null=True)),
                ('tempo_stimato', models.IntegerField()),
                ('is_completato', models.BooleanField(default=False)),
                ('timestamp_creazione', models.FloatField(blank=True, null=True)),
                ('n_posti_disp', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Progetto',
                'verbose_name_plural': 'Progetti',
            },
        ),
        migrations.CreateModel(
            name='BaseDataUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ruolo', models.CharField(choices=[('STUD', 'Studente'), ('PROF', 'Professore'), ('SUPV', 'Supervisore')], max_length=4)),
                ('codFiscale', models.CharField(max_length=16)),
                ('DataNascita', models.CharField(max_length=32)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Filiale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(max_length=64)),
                ('n_civico', models.CharField(max_length=8)),
                ('comune', models.CharField(max_length=32)),
                ('citta', models.CharField(max_length=32)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiali', to='app.azienda')),
            ],
            options={
                'verbose_name': 'Filiale',
                'verbose_name_plural': 'Filiali',
            },
        ),
        migrations.CreateModel(
            name='Proff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proff',
                'verbose_name_plural': 'Proff',
            },
        ),
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_presa_incarico_p', models.FloatField(blank=True, null=True)),
                ('matricola', models.CharField(max_length=5)),
                ('anno_scolastico', models.IntegerField()),
                ('sezione', models.CharField(max_length=2)),
                ('tot_ore_pcto', models.IntegerField()),
                ('progetto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partecipare', to='app.progetto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Studente',
                'verbose_name_plural': 'Studenti',
            },
        ),
        migrations.CreateModel(
            name='StoricoProgettoStudente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_abbandono', models.FloatField()),
                ('progetto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progetto', to='app.progetto')),
                ('studente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ha_partecipato', to='app.studente')),
            ],
            options={
                'verbose_name': 'StoricoProgettoStudente',
                'verbose_name_plural': 'StoricoProgettoStudente',
            },
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diari', to='app.proff')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diari', to='app.studente')),
            ],
            options={
                'verbose_name': 'Voce Diario',
                'verbose_name_plural': 'Voci Diario',
            },
        ),
        migrations.CreateModel(
            name='SupervisoreAzienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestire', to='app.filiale')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SupervisoreAzienda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SupervisoreAzienda',
                'verbose_name_plural': 'SupervisoreAzienda',
            },
        ),
        migrations.AddField(
            model_name='progetto',
            name='supervisore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progetti', to='app.supervisoreazienda'),
        ),
        migrations.CreateModel(
            name='PaginaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenuto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagine', to='app.diario')),
                ('supervisore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifica', to='app.supervisoreazienda')),
            ],
            options={
                'verbose_name': 'Pagina Diario',
                'verbose_name_plural': 'Pagine Diario',
                'ordering': ['-data'],
            },
        ),
    ]
