# Generated by Django 5.0.7 on 2025-01-21 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targa', models.CharField(max_length=10, unique=True)),
                ('colore', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Auto',
            },
        ),
        migrations.CreateModel(
            name='Guidatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_fisc', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Guidatore',
                'verbose_name_plural': 'Guidatori',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione_evento', models.CharField(max_length=200)),
                ('datetime', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vigile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricola', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Vigile',
                'verbose_name_plural': 'Vigili',
            },
        ),
        migrations.CreateModel(
            name='Contravvenzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luogo', models.CharField(max_length=200)),
                ('datetime', models.CharField(max_length=200)),
                ('tipo_infrazione', models.CharField(max_length=100)),
                ('importo', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.auto')),
                ('guidatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.guidatore')),
                ('vigile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vigile')),
            ],
            options={
                'verbose_name': 'Contravvenzione',
                'verbose_name_plural': 'Contravvenzioni',
            },
        ),
    ]
