# Generated by Django 5.0.7 on 2025-02-22 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcname', models.CharField(max_length=255)),
                ('timestamp', models.FloatField(unique=True)),
                ('os', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DiskDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_disk', models.BigIntegerField()),
                ('disk_free', models.BigIntegerField()),
                ('disk_name', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agentdb')),
            ],
        ),
    ]
