# Generated by Django 5.0.7 on 2025-06-04 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.CreateModel(
            name='DirectoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('last_modify_date', models.DateField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectories', to='app.directoryuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DirectoryUser',
                'verbose_name_plural': 'DirectoryUsers',
            },
        ),
        migrations.CreateModel(
            name='FileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('creation_date', models.DateField()),
                ('last_modify_date', models.DateField()),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='app.directoryuser')),
            ],
            options={
                'verbose_name': 'FileUser',
                'verbose_name_plural': 'FileUsers',
            },
        ),
    ]
